# Generated by Django 5.0.6 on 2025-06-25 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobMatcher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
